### ISSUE TITLE
The configuration is not working anymore

### ISSUE THREAD

**Issue by S-Polimetla** [nathanpeck/aws-cloudformation-fargate#16]
I might be wrong here but I could not find any explanation for this.  

I have created this repo https://github.com/S-Polimetla/aws-ecs-springboot based on the description here.  I put all of them together and made it through a pipeline. When I created this, it was working as it should be (Oct 2019). Now I had a same use case and I tried to use this.  Unfortunately, it does not work anymore.  The following is the error. 

`
Unable to assume the service linked role. Please verify that the ECS service linked role exists.
`

To reproduce this, you may upload the pipeline file in the repository with some minor changes (github token).

I do not know what is the causing this error and why now?

**Comment by S-Polimetla** [comment]
**Update**

I tried doing it in 2 seperate stacks just like the tutorial and the error persists. 

Below is the screenshot.

![image](https://user-images.githubusercontent.com/38424697/74440006-80f28280-4e6d-11ea-8e68-5a67a3dc49ca.png)

Like I said, it was working well before and now seems be an error. Could someone point out what could have gone wrong?

**Comment by dougtoppin** [comment]
@S-Polimetla I do not know for certain if this is related or not but if I run cfn-lint on template.yaml this appears (in addition to a few simple others)

```
E3008 Property "ExecutionRoleArn" has no valid Refs to Resources at Resources/Task/Properties/ExecutionRoleArn/Ref
template.yaml:138:7
```

I can't explain it yet and will try to get back to it this weekend to look more closely.
This is the execution role and not the service role so it may have nothing to do with it but it did seem unusual.

**Comment by nathanpeck** [comment]
This is because if you have ever used ECS from the console it automatically
created the service linked role for you, but if you have not yet then the
role doesn’t exist yet. Simply execute this command in your AWS CLI aws iam
create-service-linked-role --aws-service-name ecs.amazonaws.com

**Comment by dougtoppin** [comment]
I did not know this. The implication might be that in a new account there might be resources such as this that do not exist if CloudFormation is used before any cli or console create actions occur.

https://docs.aws.amazon.com/AmazonECS/latest/developerguide/using-service-linked-roles.html#create-service-linked-role

**Comment by S-Polimetla** [comment]
I have created a TaskDefinition using console and now it is all working fine as a Service linked role was created in the process. 

I would have assumed that CloudFormation creates such role based on the necessity just like when it does during a console action but it does not seem to be the case.

Thank you for the solution.
