### ISSUE TITLE
Trouble with service linked role

### ISSUE THREAD

**Issue by pete-woods** [nathanpeck/aws-cloudformation-fargate#3]
I created a user with the various permissions assigned to run the templates, but get the following error when running the actual deployment:
```Unable to assume the service linked role. Please verify that the ECS service linked role exists. (Service: AmazonECS; Status Code: 400; Error Code: InvalidParameterException; Request ID: XXXXXXXXXXX```

Then made two CLI invocations as follows:
```
aws cloudformation create-stack \
    --stack-name dev \
    --template-body file://$PWD/fargate-networking-stacks/public-private-vpc.yml \
    --capabilities CAPABILITY_IAM
```
(waited for stack to complete)
Then:
```
aws cloudformation create-stack \
    --stack-name dev-deployment \
    --template-body file://$PWD/service-stacks/private-subnet-public-loadbalancer.yml \
    --parameters ParameterKey=StackName,ParameterValue=dev
```

Any suggestions about what I might have done wrong for AWS not to find the role that has clearly been created by the first command?

**Comment by pete-woods** [comment]
Never mind. Just had to create the service linked role for my account:
```aws iam create-service-linked-role --aws-service-name ecs.amazonaws.com```

**Comment by pete-woods** [comment]
Just wanted to say "thanks" for these great templates, too! Really helped me get going much quicker than I would have from just the docs.

**Comment by nathanpeck** [comment]
Sure thing @pete-woods! Thanks a lot for using them!

**Comment by dinvlad** [comment]
Another way to do it is through https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-servicelinkedrole.html
